# Generated by Django 6.0.3 on 2026-03-09 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('promo_type', models.CharField(choices=[('spend_threshold', 'Spend Threshold Discount'), ('free_gift', 'Free Gift with Purchase'), ('buy_n_get_n', 'Buy N Get N Free'), ('bundle', 'Bundle Discount')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpendThresholdPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_cart_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed $'), ('percent', 'Percentage %')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BundlePromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('products', models.ManyToManyField(related_name='bundle_promos', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='FreeGiftPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_quantity', models.PositiveIntegerField(default=1)),
                ('gift_quantity', models.PositiveIntegerField(default=1)),
                ('gift_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_as_free_gift', to='inventory.product')),
                ('trigger_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers_free_gift', to='inventory.product')),
            ],
        ),
    ]
