# Generated by Django 6.0.3 on 2026-03-09 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('promotions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotion',
            name='joint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.joint'),
        ),
        migrations.AddField(
            model_name='freegiftpromo',
            name='promotion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='free_gift', to='promotions.promotion'),
        ),
        migrations.AddField(
            model_name='bundlepromo',
            name='promotion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bundle', to='promotions.promotion'),
        ),
        migrations.AddField(
            model_name='spendthresholdpromo',
            name='promotion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spend_threshold', to='promotions.promotion'),
        ),
    ]
