# Generated by Django 6.0.3 on 2026-03-13 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_productfreeaccessory'),
        ('promotions', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bundles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('joints', models.ManyToManyField(blank=True, help_text='Select branches. Leave empty to make available in ALL branches.', related_name='bundles', to='inventory.joint')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_free', models.BooleanField(default=False, help_text='If True, this item is shown at $0 on the receipt (price absorbed into bundle)')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='promotions.bundle')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_bundles', to='inventory.product')),
            ],
            options={
                'ordering': ['is_free', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CategoryTierFreeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal label, e.g. "Glasses tier 1 (<$12)"', max_length=120)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for no upper limit (i.e. $X and above)', max_digits=10, null=True)),
                ('label', models.CharField(blank=True, help_text='Label shown on cart / receipt, e.g. "Free pouch & wipe"', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(help_text='Products in this category trigger the rule', on_delete=django.db.models.deletion.CASCADE, related_name='tier_free_rules', to='inventory.category')),
                ('joint', models.ForeignKey(blank=True, help_text='Leave blank to apply to ALL branches', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tier_free_rules', to='inventory.joint')),
            ],
            options={
                'verbose_name': 'Category tier free rule',
                'ordering': ['category', 'min_price'],
            },
        ),
        migrations.CreateModel(
            name='CategoryTierFreeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_free_by_tier', to='inventory.product')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_items', to='promotions.categorytierfreerule')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
