# Generated by Django 4.2.28 on 2026-03-02 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Joint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('eyedentity', 'Eyedentity'), ('genx', 'GenX'), ('armor_sole', 'Armor Sole')], help_text='The name/identifier of this shop.', max_length=50, unique=True)),
                ('display_name', models.CharField(help_text="Full display name, e.g. 'Eyedentity - Zee Eyewear'", max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('uses_product_codes', models.BooleanField(default=False, help_text='Eyedentity and Armor Sole use product codes; GenX does not.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Product code (required for Eyedentity and Armor Sole).', max_length=50, null=True)),
                ('name', models.CharField(help_text='Product name or description.', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling price in USD.', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from sales without deleting.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.joint')),
            ],
            options={
                'ordering': ['joint', 'name'],
                'unique_together': {('joint', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StockTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conducted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('conducted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_takes_conducted', to=settings.AUTH_USER_MODEL)),
                ('joint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_takes', to='inventory.joint')),
            ],
            options={
                'ordering': ['-conducted_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('transferred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('from_joint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='inventory.joint')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('to_joint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='inventory.joint')),
                ('transferred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transferred_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTakeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_count', models.IntegerField(help_text='What the system showed before the stock take.')),
                ('actual_count', models.IntegerField(help_text='The physical count during the stock take.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('stock_take', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktake')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text='Current quantity in stock.')),
                ('last_stock_take', models.DateTimeField(blank=True, help_text='Date and time of the last monthly stock take.', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Stock Level',
            },
        ),
    ]
