# Generated by Django 6.0.3 on 2026-03-09 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktake',
            name='conducted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_takes_conducted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='joint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_takes', to='inventory.joint'),
        ),
        migrations.AddField(
            model_name='stocktakeitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='stocktakeitem',
            name='stock_take',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktake'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='from_joint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='inventory.joint'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='to_joint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='inventory.joint'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='transferred_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stock',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='inventory_p_barcode_3a77e5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['joint', 'is_active'], name='inventory_p_joint_i_ff36d3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_clearance'], name='inventory_p_is_clea_347272_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['joint', 'is_active', 'is_clearance'], name='inventory_p_joint_i_6d0a33_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('joint', 'code')},
        ),
    ]
