# Generated by Django 4.2.28 on 2026-03-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_user_fks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joint',
            name='display_name',
            field=models.CharField(help_text="Full display name, e.g. 'Eyedentity - Zee Eyewear'", max_length=100),
        ),
        migrations.AlterField(
            model_name='joint',
            name='uses_product_codes',
            field=models.BooleanField(default=False, help_text='Eyedentity and Armor Sole use product codes; GenX does not.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, help_text='Product code (required for Eyedentity and Armor Sole).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide from sales without deleting.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Product name or description.', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price in USD.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_stock_take',
            field=models.DateTimeField(blank=True, help_text='Date and time of the last monthly stock take.', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Current quantity in stock.'),
        ),
        migrations.AlterField(
            model_name='stocktakeitem',
            name='actual_count',
            field=models.IntegerField(help_text='The physical count during the stock take.'),
        ),
        migrations.AlterField(
            model_name='stocktakeitem',
            name='system_count',
            field=models.IntegerField(help_text='What the system showed before the stock take.'),
        ),
    ]
