# Generated by Django 6.0.3 on 2026-03-11 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFreeAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='How many free units come with each unit of the trigger product')),
                ('label', models.CharField(blank=True, help_text='Receipt label, e.g. "Free case with purchase". Defaults to accessory name.', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('accessory_product', models.ForeignKey(help_text='The product given for free (must belong to same joint)', on_delete=django.db.models.deletion.CASCADE, related_name='given_as_free_with', to='inventory.product')),
                ('trigger_product', models.ForeignKey(help_text='When this product is added to cart, the accessory is auto-added for free', on_delete=django.db.models.deletion.CASCADE, related_name='free_accessories', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Free Accessory Bundle',
                'verbose_name_plural': 'Free Accessory Bundles',
                'ordering': ['trigger_product__name'],
                'constraints': [models.UniqueConstraint(fields=('trigger_product', 'accessory_product'), name='unique_trigger_accessory_pair')],
            },
        ),
    ]
