# Generated by Django 6.0.3 on 2026-04-03 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_productfreeaccessory'),
        ('sales', '0006_saleitem_custom_item_name_saleitem_item_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('color', models.CharField(blank=True, default='#7c3aed', max_length=20)),
            ],
            options={
                'verbose_name': 'Product Tag',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductSerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('returned', 'Returned'), ('defective', 'Defective')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='inventory.product')),
                ('sold_in_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serial_numbers', to='sales.saleitem')),
            ],
            options={
                'verbose_name': 'Product Serial Number',
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('expiring', 'Expiring Soon'), ('overstock', 'Overstock')], max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('joint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='inventory.joint')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Stock Alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('sale', 'Sale'), ('return', 'Return / Restock'), ('adjustment', 'Manual Adjustment'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('stock_take', 'Stock Take'), ('purchase_receipt', 'Purchase Receipt'), ('damage_write_off', 'Damage / Write-Off')], max_length=25)),
                ('quantity', models.IntegerField(help_text='Positive = in, Negative = out')),
                ('reference_id', models.CharField(blank=True, help_text='Receipt #, GRN #, etc.', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('stock_before', models.IntegerField()),
                ('stock_after', models.IntegerField()),
                ('joint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.joint')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-timestamp'],
            },
        ),
    ]
