# Generated by Django 6.0.3 on 2026-04-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_producttag_productserialnumber_stockalert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktake',
            name='status',
            field=models.CharField(default='completed', max_length=20),
        ),
    ]
