# Generated by Django 4.2.26 on 2026-04-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stocktake_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktakeitem',
            name='variance',
            field=models.IntegerField(default=0),
        ),
    ]
