# Generated by Django 6.0.3 on 2026-03-12 08:10

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_productfreeaccessory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('full', 'Full Day')], default='full', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('disputed', 'Disputed')], default='open', max_length=20)),
                ('shift_date', models.DateField(default=django.utils.timezone.localdate)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('opening_float', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('expected_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('expected_ecocash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('expected_card', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('expected_mixed_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('expected_mixed_ecocash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('actual_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('actual_ecocash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('actual_card', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('cash_denomination_100', models.PositiveIntegerField(default=0)),
                ('cash_denomination_50', models.PositiveIntegerField(default=0)),
                ('cash_denomination_20', models.PositiveIntegerField(default=0)),
                ('cash_denomination_10', models.PositiveIntegerField(default=0)),
                ('cash_denomination_5', models.PositiveIntegerField(default=0)),
                ('cash_denomination_2', models.PositiveIntegerField(default=0)),
                ('cash_denomination_1', models.PositiveIntegerField(default=0)),
                ('cash_denomination_cents', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('expenses_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('expenses_ecocash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('manager_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_ups_approved', to=settings.AUTH_USER_MODEL)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_ups_submitted', to=settings.AUTH_USER_MODEL)),
                ('joint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_ups', to='inventory.joint')),
            ],
            options={
                'verbose_name': 'Cash-Up',
                'verbose_name_plural': 'Cash-Ups',
                'ordering': ['-shift_date', '-opened_at'],
                'unique_together': {('joint', 'cashier', 'shift_date', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='CashUpAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict)),
                ('cash_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='cashup.cashup')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
