# Generated by Django 4.2.28 on 2026-03-02 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('ecocash', 'EcoCash'), ('card', 'Card'), ('mixed', 'Mixed (Cash + EcoCash)')], default='cash', max_length=20)),
                ('sale_type', models.CharField(choices=[('system', 'System Sale'), ('manual', 'Manual Sale (Receipt Upload)')], default='system', max_length=20)),
                ('manual_receipt_image', models.ImageField(blank=True, help_text='Photo of the manual receipt (for manual sales only).', null=True, upload_to='manual_receipts/%Y/%m/')),
                ('customer_name', models.CharField(blank=True, help_text='Optional customer name.', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('receipt_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('joint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='inventory.joint')),
                ('sold_by', models.ForeignKey(help_text='The staff member who processed this sale.', on_delete=django.db.models.deletion.PROTECT, related_name='sales_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at time of sale (snapshot, in case price changes later).', max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='sales.sale')),
            ],
        ),
        migrations.CreateModel(
            name='SaleAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='created', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict, help_text='JSON snapshot of the sale at creation time.')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='audit_log', to='sales.sale')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
