# Generated by Django 6.0.3 on 2026-03-09 05:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='created', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_free_gift', models.BooleanField(default=False)),
                ('promotion_label', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('ecocash', 'EcoCash'), ('card', 'Card'), ('mixed', 'Mixed (Cash + EcoCash)')], default='cash', max_length=20)),
                ('sale_type', models.CharField(choices=[('system', 'System Sale'), ('manual', 'Manual Sale (Receipt Upload)'), ('pos', 'POS Sale')], default='system', max_length=20)),
                ('manual_receipt_image', models.ImageField(blank=True, null=True, upload_to='manual_receipts/%Y/%m/')),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('receipt_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_type', models.CharField(blank=True, choices=[('fixed', 'Fixed $'), ('percent', 'Percentage %')], max_length=20)),
                ('discount_label', models.CharField(blank=True, max_length=200)),
                ('is_held', models.BooleanField(default=False)),
                ('held_at', models.DateTimeField(blank=True, null=True)),
                ('joint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='inventory.joint')),
                ('promotion_applied', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='promotions.promotion')),
            ],
            options={
                'ordering': ['-sale_date'],
            },
        ),
    ]
