# Generated by Django 6.0.3 on 2026-03-09 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sold_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saleauditlog',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saleauditlog',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='audit_log', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='sales.sale'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['joint', 'sale_date'], name='sales_sale_joint_i_f26b33_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sold_by', 'sale_date'], name='sales_sale_sold_by_db7d84_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['is_held'], name='sales_sale_is_held_761af8_idx'),
        ),
    ]
