# Generated by Django 6.0.3 on 2026-03-12 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0004_alter_sale_sold_by_alter_saleauditlog_performed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cash_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='customers.customer'),
        ),
    ]
