# Generated by Django 6.0.3 on 2026-03-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_sale_cash_amount_sale_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='custom_item_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='item_note',
            field=models.TextField(blank=True),
        ),
    ]
